cmake_minimum_required (VERSION 3.10 FATAL_ERROR)

project (TreeOp)
set (CMAKE_CXX_STANDARD 17)

set (OUTPUT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/output")
set (CMAKE_RUNTIME_OUTPUT_DIRECTORY ${OUTPUT_DIR}/bin)
set (CMAKE_LIBRARY_OUTPUT_DIRECTORY ${OUTPUT_DIR}/lib)
set (CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${OUTPUT_DIR}/lib)

file (GLOB TARGET_SRC "src/*.cpp")

add_executable (${PROJECT_NAME} ${TARGET_SRC})

set_target_properties(TreeOp PROPERTIES
    VS_DEBUGGER_COMMAND_ARGUMENTS "simple.code"
    VS_DEBUGGER_WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}/examples"
)
